### ISSUE TITLE
Bumps causing crash

### ISSUE THREAD

**Issue by c1charge** [shane-mason/FieldStation42#169]
I am not sure if this is related to #160, as that was what I was following and thinking was the issue. It appears, when attempting to play a .mp4 bump, I am getting a crash. I have to alt + f4 to get back to desktop environment. This is the output in the cmd:
```

2025-05-23 13:52:36,039 INFO:FieldPlayer:Playing entry PlanEntry: catalog/ToonSpree_catalog/bump/post/back_long_bump.mp4 skip=0 duration=10.079773
2025-05-23 13:52:36,039 INFO:FieldPlayer:Initial Skip: 0
Traceback (most recent call last):
  File "/home/brandon/FieldStation42/field_player.py", line 217, in <module>
    main_loop(trans_fn)
  File "/home/brandon/FieldStation42/field_player.py", line 77, in main_loop
    outcome = player.play_slot(channel_conf['network_name'],datetime.datetime.now())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 140, in play_slot
    return self._play_from_point(play_point)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 153, in _play_from_point
    self.play_file(entry.path)
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 100, in play_file
    self.mpv.play(file_path)
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 617, in play
    self.loadfile(url)
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 607, in wrapper
    return self.command(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 640, in command
    return self.mpv_inter.command(command, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 335, in command
    self.socket.send({"command":command_list, "request_id": command_id})
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 164, in send
    self.socket.send(json.dumps(data).encode('utf-8') + b'\n')
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

I also attempted to start with this command: 

`python3 field_player.py -v -l mylog.txt`

But I could not find a mylog.txt created anywhere.
I just got this up and running today, but from what I can tell I have followed everything correctly. The .json files are correct and schedules seem correct. I have included the .json conf file for this channel.

[ToonSpree.json](https://github.com/user-attachments/files/20416308/ToonSpree.json)

**Comment by c1charge** [comment]
Used `mpv "catalog/ToonsSpree_catalog/bump/post/back_long_bump.mp4"` and the video plays correctly.

**Comment by ddrfr33k** [comment]
Yeah, that looks an awful lot like my issue...

**Comment by shane-mason** [comment]
This is great - thanks for providing the log output! I can work with this - will have a look at it shortly and get back to you.

**Comment by ekalkst** [comment]
> Furthermore, are bumps required? I cant seem to create a schedule without them, but I crash with them.

I just put up a [PR](https://github.com/shane-mason/FieldStation42/pull/168)  to work around this type of thing. I have my fs42 setup for no commercials or bumps.  You just need to pass an empty string in your json for bump_dir. It works without the PR but the catalog will make a duplicate item of the same show without the code change

**Comment by c1charge** [comment]
@ekalkst Thanks, ill look into that for the time being.
@shane-mason thank you, I think there may be a bigger issue or I am just have a combo of two issues... just for your radar I have been messing with it more, and I have gotten a pretty repeatable bug. Switching back and forth (and sometimes not even switching) and going into commercials I am getting another copied error bellow. I have gotten this multiple times now.

```
2025-05-23 15:09:54,462 INFO:FieldPlayer:Playing entry PlanEntry: catalog/ToonSpree_catalog/movie/Monster House.mp4 skip=340.2738041875 duration=340.2738041875
2025-05-23 15:09:54,462 INFO:FieldPlayer:Initial Skip: 113.535452
2025-05-23 15:09:54,567 INFO:FieldPlayer:Seeking for: 453.8092561875
2025-05-23 15:09:54,568 INFO:FieldPlayer:Monitoring for: 226.73835218749997
2025-05-23 15:10:30,541 DEBUG:MainLoop:Got player outcome:PlayStatus.CHANNEL_CHANGE
2025-05-23 15:10:30,542 DEBUG:MainLoop:Got channel down command
2025-05-23 15:10:30,667 INFO:MainLoop:Playing station: Neo_Toonami
2025-05-23 15:10:30,669 INFO:MainLoop:Starting station Neo_Toonami at: friday 15 skipping=630 
2025-05-23 15:10:30,670 INFO:FieldPlayer:Playing entry PlanEntry: catalog/Neo_Toonami_catalog/commercial/common_commercials/90s Commercials - S02.E1.mp4 skip=0 duration=29.796433
2025-05-23 15:10:30,670 INFO:FieldPlayer:Initial Skip: 2.582839
Traceback (most recent call last):
  File "/home/brandon/FieldStation42/field_player.py", line 217, in <module>
    main_loop(trans_fn)
  File "/home/brandon/FieldStation42/field_player.py", line 77, in main_loop
    outcome = player.play_slot(channel_conf['network_name'],datetime.datetime.now())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 140, in play_slot
    return self._play_from_point(play_point)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 153, in _play_from_point
    self.play_file(entry.path)
  File "/home/brandon/FieldStation42/fs42/station_player.py", line 100, in play_file
    self.mpv.play(file_path)
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 617, in play
    self.loadfile(url)
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 607, in wrapper
    return self.command(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 640, in command
    return self.mpv_inter.command(command, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 335, in command
    self.socket.send({"command":command_list, "request_id": command_id})
  File "/home/brandon/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 164, in send
    self.socket.send(json.dumps(data).encode('utf-8') + b'\n')
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable

```

I didnt see anything super useful in the log.txt file, but ill include it anyway. It shows some of my previous attempts and switching channels and such. (I still feel like this may be connected to the 160 issue... but i'm not that smart :p ) Anyway... Appreciate your work!

[mylog.txt](https://github.com/user-attachments/files/20417160/mylog.txt)

**Comment by shane-mason** [comment]
I think @ekalkst PR will fix one of the issues.  But there are two more issues here:

* Posix path being sent to json encoder vs a string
* Error on MPV play - which I think is likely ALSO due to a posix path vs a string. 

I think this will keep coming up in different places unless I fix it at the core. Should be quick.

**Comment by shane-mason** [comment]
Okay - I think this is corrected. If do a fresh pull, rebuild your catalog and sequences (if you have any) it should work better.

I just made a change so that nothing gets stored as posix paths but as strings so we should not have any more of the json errors due to serialization. I also merged @ekalkst PR to fix the issue when you aren't using bumps or commercials.

**Comment by xwcg** [comment]
FYI Dunno if this belongs here but it seems adjacent, it sometimes seems to get the wrong duration for shows:

`2025-05-23 22:47:32,512 INFO:MainLoop:Playing station: SaiFai
2025-05-23 22:47:32,517 INFO:MainLoop:Starting station SaiFai at: friday 22 skipping=2852 
2025-05-23 22:47:32,628 INFO:FieldPlayer:Playing entry PlanEntry: catalog/saifai/series/Babylon 5/S01E15 - Grail.avi skip=559.3333333333334 duration=279.6666666666667
2025-05-23 22:47:32,629 INFO:FieldPlayer:Initial Skip: 259.66416
Traceback (most recent call last):
  File "/home/fieldstation/FieldStation42/field_player.py", line 217, in <module>
    main_loop(trans_fn)
  File "/home/fieldstation/FieldStation42/field_player.py", line 77, in main_loop
    outcome = player.play_slot(channel_conf['network_name'],datetime.datetime.now())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fieldstation/FieldStation42/fs42/station_player.py", line 140, in play_slot
    return self._play_from_point(play_point)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fieldstation/FieldStation42/fs42/station_player.py", line 153, in _play_from_point
    self.play_file(entry.path)
  File "/home/fieldstation/FieldStation42/fs42/station_player.py", line 100, in play_file
    self.mpv.play(file_path)
  File "/home/fieldstation/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 617, in play
    self.loadfile(url)
  File "/home/fieldstation/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 607, in wrapper
    return self.command(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fieldstation/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 640, in command
    return self.mpv_inter.command(command, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fieldstation/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 335, in command
    self.socket.send({"command":command_list, "request_id": command_id})
  File "/home/fieldstation/FieldStation42/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 164, in send
    self.socket.send(json.dumps(data).encode('utf-8') + b'\n')
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
`

**Comment by c1charge** [comment]
My bumps are playing fine, however now when the program switched to my pre bump, it played with sound, and then everything after that has lost all sound. All commercials afterwards and the movie that was playing have no sound. All channels no longer have sound, and I have to restart the program to get it back.

**Comment by c1charge** [comment]
An update to this, not happening every time we switch to bumps, it iffy when it happens.

**Comment by shane-mason** [comment]
xwcg - I think your error is caused by the same issue I fixed able: tying to serialize posix path causing json failures. If you do a fresh pull and its still now working, let me know.

**Comment by shane-mason** [comment]
@c1charge - do you have to restart the pi of just fs42 to get sound back?

**Comment by xwcg** [comment]
@shane-mason unfortunately it is still occuring. I strongly suspect that it is unable to pull the correct duration for the video file as it is trying to skip further than the detected duration. Which is strange because the scheduler definitely scheduled the show correctly yet during playback it doesn't get the correct duration

**Comment by c1charge** [comment]
@shane-mason just the fs42, not the pi.

**Comment by shane-mason** [comment]
@xwcg - I would like to split your issue out since I think it is separate. I have created new issue #171 - if you can follow that ticket, I have a question and some suggestions.

**Comment by ddrfr33k** [comment]
Yup, that did it! That's what I needed. Commercials are working now!

**Comment by shane-mason** [comment]
@c1charge - I am suspecting that the sound issue is an mpv or OS issue. Since I introduced a bug that manifested itself in a couple of different ways, its made getting to the bottom of this a little more challenging. Can you do the following just to clear out any remaining issues that might be caused by the posix path bug?

```
git pull
rm runtime/*.bin
python3 station_42.py --rebuild_catalog
python3 station_42.py --rebuild_sequences
python3 station_42.py --add_month
```

if it still happens, is it only happening after a pre-bump is played, or can it happen at other times?

**Comment by ekalkst** [comment]
I dont have this problem on my normal setup (intel NUC running ubuntu 22.04)  But i came across the same?(or similar problem) on my framework laptop running 24.04.  Thought maybe newer python was a potential issue but i used pyenv to match my NUC python version of 3.10.x and got the error:

`2025-05-24 14:30:51,008 INFO:FieldPlayer:Playing entry PlanEntry: catalog/cartoon/south_park/South Park S11/11.06 - D-Yikes.mp4 skip=0 duration=1325.4087
2025-05-24 14:30:51,009 INFO:FieldPlayer:Initial Skip: 480.038502
Traceback (most recent call last):
File "/home/eric/SM_FieldStation42/field_player.py", line 217, in <module>
main_loop(trans_fn)
File "/home/eric/SM_FieldStation42/field_player.py", line 77, in main_loop
outcome = player.play_slot(channel_conf['network_name'],datetime.datetime.now())
File "/home/eric/SM_FieldStation42/fs42/station_player.py", line 140, in play_slot
return self._play_from_point(play_point)
File "/home/eric/SM_FieldStation42/fs42/station_player.py", line 153, in _play_from_point
self.play_file(entry.path)
File "/home/eric/SM_FieldStation42/fs42/station_player.py", line 100, in play_file
self.mpv.play(file_path)
File "/home/eric/SM_FieldStation42/.venv/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 617, in play
self.loadfile(url)
File "/home/eric/SM_FieldStation42/.venv/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 607, in wrapper
return self.command(name, *args)
File "/home/eric/SM_FieldStation42/.venv/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 640, in command
return self.mpv_inter.command(command, *args)
File "/home/eric/SM_FieldStation42/.venv/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 335, in command
self.socket.send({"command":command_list, "request_id": command_id})
File "/home/eric/SM_FieldStation42/.venv/lib/python3.10/site-packages/python_mpv_jsonipc.py", line 164, in send
self.socket.send(json.dumps(data).encode('utf-8') + b'\n')
File "/home/eric/.pyenv/versions/3.10.17/lib/python3.10/json/init.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/home/eric/.pyenv/versions/3.10.17/lib/python3.10/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/home/eric/.pyenv/versions/3.10.17/lib/python3.10/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/home/eric/.pyenv/versions/3.10.17/lib/python3.10/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.class.name} '
TypeError: Object of type PosixPath is not JSON serializable`

I am matching main branch as of now, so those previous commits are there and I still saw it.  I was rubberducking through the problem, and i tried adding this to [play_file](https://github.com/shane-mason/FieldStation42/blob/main/fs42/station_player.py#L99-L101)

```
        if hasattr(file_path, '__fspath__'):
            file_path = str(file_path)
        self.mpv.play(file_path)
```

And it seemed to stopped the error.  For my case I do not have any bumps or commercials.  It was happening on channel change. After a certain amount of changes it would then stop changing channels and the logs were showing the above error.  I'm not 100% sure but it kept happening on a certain file, so maybe the posix of the json path conversion goes wonky on certain filenames? Or the conversion that happens in _rfind_media is bugging out on some paths?

**Comment by shane-mason** [comment]
@ekalkst  - I don't think so - then we would see a string based error but its still passing the posix path rather than a string. 

Its not related to the main problem in this thread, since the topic here is that sound is cutting out. I think I have a solution to what you are seeing over in #171 - which is about the serialization error in json ipc. If there is still a problem, I want to get to the core of it, otherwise there are a lot of places it could keep expressing itself. Let's follow up in #171

**Comment by c1charge** [comment]
@shane-mason I have been messing around with it today, and ran the commands as you requested. The problem keeps occuring, and every time I have caught it it has been from playing a bump. It seems forcing it to play different videos (from like channel switching) can bring the sound back for all channels after 3 or 4 switches. But this is happening with any bumps from what I can tell.

**Comment by c1charge** [comment]
And to be clear, it's not everytime we go into a bump, but often enough I can catch it happening multiple times in one session
